version: "3.8"
services:
  ams-front:
    container_name: ams-front
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 4200:80
    volumes:
      - ./:/usr/local/app/frontend
    command: nginx -g "daemon off;"
