version: '3.8'
services:
    ipl-api:
        container_name: ipl-api
        build: .
        environment:
            - MONGO_HOST=amss-db
            - COMPOSE_PROJECT_NAME=ipl
        ports:
            - 3000:3000
        volumes:
            - ../psvolumes/ipl/uploads:/workspace/uploads
        depends_on:
            - amss-db
        networks:
            - hrm_network
        restart: unless-stopped
        links:
            - amss-db
        command: npm start

    amss-db:
        container_name: amss-db
        image: mongo:6
        volumes:
            - ../psvolumes/amss-db:/data/db
        environment:
            - COMPOSE_PROJECT_NAME=ipl
            - MONGO_INITDB_ROOT_USERNAME=
            - MONGO_INITDB_ROOT_PASSWORD=
        ports:
            - 27019:27017
        networks:
            - hrm_network
        restart: unless-stopped
networks:
    hrm_network:
        driver: bridge
